name: ci # 


on:
  push:
    branches: # 


      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2.3.1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v2.3.1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install mkdocs-material 
        pip install mkdocstrings==0.19.0
        pip install markdown-include
        pip install -q 'setupext-janitor' #
        pip install pytkdocs[numpy-style]
        mkdocs gh-deploy --force
        pytest
